name: Testing builds on different systems

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Update packages"
      run: |
        sudo apt-get update

    - name: "Install: make"
      run: |
        sudo apt-get install -y make
        make --version

    - name: "Install: makefile2graph"
      run: |
        sudo apt-get install -y makefile2graph
        dpkg -l makefile2graph

    - name: "Install: graphviz"
      run: |
        sudo apt-get install -y graphviz
        dot -V

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Install: make"
      run: |
        brew install make
        make --version

    - name: "Install: makefile2graph"
      run: |
        brew install makefile2graph

    - name: "Install: graphviz"
      run: |
        brew install graphviz
        dot -V

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Install: make"
      run: |
        choco install make
        make --version

#   TODO: Not exists :(
#    - name: "Install: makefile2graph"
#      run: |
#        choco install makefile2graph

    - name: "Install: graphviz"
      run: |
        choco install graphviz
        dot -V
