name: Testing builds on different systems

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: "Update packages"
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update

    - name: "make: Install on Ubuntu"
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y make
        make --version

    - name: "makefile2graph: Install on Ubuntu"
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y makefile2graph
        dpkg -l makefile2graph

    - name: "graphviz: Install on Ubuntu"
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y graphviz
        dpkg -l graphviz

    - name: Install make on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install make
        make --version

    - name: Install make on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        make --version
